import { ChevronRight, ShoppingBag } from 'lucide-react';
import type { Mode, Store, View } from '../types';

interface Props { mode: Mode; setMode: (mode: Mode) => void; cartCount: number; cartTotal: number; onOpenCart: () => void; selectedStore?: Store; currentView: View; onBack: () => void; }
export function HeaderNavbar({ mode, setMode, cartCount, cartTotal, onOpenCart, selectedStore, currentView, onBack }: Props) {
  return <header className="sticky top-0 z-40 bg-orange-600 text-white shadow-lg"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-16">
    <div className="flex items-center gap-3"><button onClick={onBack} className="flex items-center gap-2 font-bold text-xl"><span className="w-9 h-9 rounded-xl bg-white text-orange-600 flex items-center justify-center">K</span><span className="hidden sm:inline">KantinOnline</span></button>{currentView === 'store_detail' && selectedStore && <div className="hidden md:flex items-center text-xs text-orange-100 bg-orange-700/60 px-3 py-1.5 rounded-full"><span>Daftar Toko</span><ChevronRight className="w-3 h-3 mx-1"/><span className="font-semibold text-white truncate max-w-[150px]">{selectedStore.name}</span></div>}</div>
    <div className="flex items-center gap-2 sm:gap-4"><div className="bg-orange-700/80 p-1 rounded-full flex items-center text-xs sm:text-sm"><button onClick={() => setMode('mahasiswa')} className={`px-3 py-1.5 rounded-full ${mode === 'mahasiswa' ? 'bg-white text-orange-700' : 'text-orange-100'}`}>🎓 <span className="hidden sm:inline">Mode Mahasiswa</span></button><button onClick={() => setMode('penjual')} className={`px-3 py-1.5 rounded-full ${mode === 'penjual' ? 'bg-slate-900 text-white' : 'text-orange-100'}`}>🏪 <span className="hidden sm:inline">Mode Penjual</span></button></div>{mode === 'mahasiswa' && <button onClick={onOpenCart} className="relative bg-orange-700 px-3 py-2 rounded-xl flex items-center gap-2"><ShoppingBag className="w-5 h-5"/><span className="hidden sm:inline text-xs">Rp {cartTotal.toLocaleString('id-ID')}</span>{cartCount > 0 && <span className="absolute -top-2 -right-2 bg-yellow-400 text-slate-900 text-xs font-black w-5 h-5 rounded-full flex items-center justify-center">{cartCount}</span>}</button>}</div>
  </div></div></header>;
}
