import { useMemo } from 'react';
import { ChevronRight, Clock, Plus, Search, Star, Store, UtensilsCrossed, X } from 'lucide-react';
import { STORE_CATEGORIES } from '../data';
import type { Store as StoreType } from '../types';
interface Props { stores: StoreType[]; onSelect: (id: string) => void; onAdd: () => void; search: string; setSearch: (value: string) => void; category: string; setCategory: (value: string) => void; }
export function StoreDirectoryView({ stores, onSelect, onAdd, search, setSearch, category, setCategory }: Props) {
 const filtered = useMemo(() => stores.filter(s => (s.name + s.category + s.description).toLowerCase().includes(search.toLowerCase()) && (category === 'Semua' || s.category === category)), [stores, search, category]);
 return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6"><div className="bg-gradient-to-r from-orange-500 to-amber-600 rounded-3xl p-6 sm:p-8 text-white"><UtensilsCrossed className="float-right w-24 h-24 opacity-20"/><span className="text-xs font-bold uppercase">Kantin Kampus Terpadu</span><h1 className="text-2xl sm:text-4xl font-extrabold mt-3">Pesan Makanan Tanpa Antre, Ambil Langsung Di Stand!</h1><p className="text-orange-100 mt-2">Pilih stand, pesan menu favorit, dan bayar dengan mudah.</p></div>
 <div className="flex flex-col md:flex-row gap-4 items-center bg-white p-4 rounded-2xl border border-slate-200"><div className="relative flex-1 w-full"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-5 h-5"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Cari stand kantin..." className="w-full pl-10 pr-9 py-2.5 rounded-xl border border-slate-200"/>{search && <button onClick={() => setSearch('')} className="absolute right-3 top-1/2 -translate-y-1/2"><X className="w-4 h-4"/></button>}</div><div className="flex gap-1.5 overflow-x-auto">{STORE_CATEGORIES.map(c => <button key={c} onClick={() => setCategory(c)} className={`px-3 py-2 rounded-xl text-xs whitespace-nowrap ${category === c ? 'bg-orange-600 text-white' : 'bg-slate-100 text-slate-600'}`}>{c}</button>)}</div><button onClick={onAdd} className="bg-slate-900 text-white px-4 py-2.5 rounded-xl text-xs whitespace-nowrap"><Plus className="w-4 h-4 inline mr-1"/>Daftarkan Stand</button></div>
 <div><h2 className="text-xl font-bold">Daftar Stand Kantin</h2><p className="text-xs text-slate-500">Menampilkan {filtered.length} stand</p></div>{filtered.length === 0 ? <div className="bg-white rounded-2xl p-12 text-center"><Store className="w-12 h-12 text-slate-300 mx-auto"/><p className="text-sm text-slate-500">Tidak ada stand ditemukan</p></div> : <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{filtered.map(store => { const open = store.status === 'Buka'; return <div key={store.id} className="bg-white rounded-2xl border border-slate-200 overflow-hidden flex flex-col"><div className="relative h-44"><img src={store.image} alt={store.name} className="w-full h-full object-cover"/><span className={`absolute top-3 left-3 px-2 py-1 rounded-full text-xs font-bold text-white ${open ? 'bg-emerald-500' : 'bg-rose-500'}`}>{store.status}</span><span className="absolute top-3 right-3 bg-white/90 px-2 py-1 rounded-full text-xs font-bold"><Star className="w-3 h-3 text-amber-500 fill-amber-500 inline"/> {store.rating}</span></div><div className="p-5 flex-1 space-y-3"><span className="text-[10px] font-bold text-orange-600 uppercase">{store.category}</span><h3 className="text-lg font-extrabold">{store.name}</h3><p className="text-xs text-slate-500 line-clamp-2">{store.description}</p><div className="flex justify-between text-xs text-slate-500"><span><Clock className="w-3 h-3 inline text-orange-500"/> {store.estimate}</span><span>{store.location}</span></div><button disabled={!open} onClick={() => onSelect(store.id)} className={`w-full py-2.5 rounded-xl text-xs font-bold ${open ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-400'}`}>{open ? <>Pilih Toko <ChevronRight className="w-4 h-4 inline"/></> : 'Toko Sedang Tutup'}</button></div></div>; })}</div>}</div>;
}
